#ifndef PROJECT_CARDS_H
#define PROJECT_CARDS_H

enum issue_cards
{
  ISSUE_PLACEHOLDER,

  PILOT__ASTEROID_FELD,
  PILOT__NAVIGATION_ERROR,
  PILOT__BLACK_HOLE,
  PILOT__SPACE_PIRATES,
  PILOT__FLIGHT_ROUTE_UPDATE,
  PILOT__BONUS_MOVEMENT,

  COMMS__EARTH_TRANSMISSION,
  COMMS__INTERNAL_COMMS_ISSUE,
  COMMS__DISPATCH_PROBE,
  COMMS__DISTRESS_SIGNAL,
  COMMS__EXTERNAL_COMMS_ISSUE,
  COMMS__GOOD_COMMUNICATION,

  ENGIN__BROKEN_AIR_FILTER,
  ENGIN__ENGINE_MALFUNCTION,
  ENGIN__FAULTY_GENERATOR,
  ENGIN__AIR_LEAK,
  ENGIN__LIGHTING_MALFUNCTION,
  ENGIN__ITEM_BOOST,

  MEDIC__HALLUCINATING,
  MEDIC__PARANOIA,
  MEDIC__FLU_OUTBREAK,
  MEDIC__SPACE_PREGNANCY,
  MEDIC__ISOLATION,
  MEDIC__HEALTHY_CREW,

  GLOBL__LOW_RESOURCES,
  GLOBL__ITEMS_OVERUSED,
  GLOBL__GRAVITY_LEAK,
  GLOBL__CHICKEN_ON_BOARD,
  GLOBL__BROKEN_ITEMS,
  GLOBL__BACKPACK_EXTENDED,
};

enum objective_cards
{
  OBJECTIVE_PLACEHOLDER,

  ISSUE_HELPER,
  ISSUE_HELPER_ALT,
  UNHELPFUL,
  UNHELPFUL_ALT,
  MAJORITY_HELPER,
  POINT_STASH,
  ISSUE_SOLVER_5,
  ISSUE_SOLVER_10,
  ISSUE_SOLVER_15,
  BIG_ISSUE,
  CLASS_ITEMS,
  PERSONAL_ISSUE,
  CLASS_SOLVER
};

enum item_cards
{
  ITEM_PLACEHOLDER,

  PILOT__NEW_CONTROLS,
  PILOT__MAP,
  PILOT__RADAR,
  PILOT__THRUSTER_UPGRADE,
  PILOT__WINDOW_WASH,

  MEDIC__BANDAID,
  MEDIC__PAINKILLERS,
  MEDIC__ANTIBIOTICS,
  MEDIC__FIRST_AID_KIT,
  MEDIC__PAIN_KILLERS,

  ENGIN__TOOL_KIT,
  ENGIN__SCREWS,
  ENGIN__WELDING_GOGGLES,
  ENGIN__WELDER,
  ENGIN__SCREWDRIVER,

  COMMS__SCOUT_DRONE,
  COMMS__RADAR,
  COMMS__MICROPHONE,
  COMMS__RADIO,
  COMMS__UPGRADED_SPEAKERS,
};

#endif // PROJECT_CARDS_H
