#ifndef PROJECT_CARDS_H
#define PROJECT_CARDS_H

// PLEASE DON'T MOVE ANY ENUMS OUT OF THIS ORDER!
enum issue_cards
{
  ISSUE_PLACEHOLDER = -1,

  COMMS__DISPATCH_PROBE = 0,
  COMMS__DISTRESS_SIGNAL = 1,
  COMMS__EARTH_TRANSMISSION = 2,
  COMMS__EXTERNAL_COMMS_ISSUE = 3,
  COMMS__GOOD_COMMUNICATION = 4,
  COMMS__INTERNAL_COMMS_ISSUE = 5,

  ENGIN__AIR_LEAK = 6,
  ENGIN__BROKEN_AIR_FILTER = 7,
  ENGIN__ENGINE_MALFUNCTION = 8,
  ENGIN__FAULTY_GENERATOR = 9,
  ENGIN__ITEM_BOOST = 10,
  ENGIN__LIGHTING_MALFUNCTION = 11,

  MEDIC__FLU_OUTBREAK = 12,
  MEDIC__HALLUCINATING = 13,
  MEDIC__HEALTHY_CREW = 14,
  MEDIC__ISOLATION = 15,
  MEDIC__PARANOIA = 16,
  MEDIC__SPACE_PREGNANCY = 17,

  GLOBL__BACKPACK_EXTENDED = 18,
  GLOBL__BROKEN_ITEMS = 19,
  GLOBL__CHICKEN_ON_BOARD = 20,
  GLOBL__GRAVITY_LEAK = 21,
  GLOBL__ITEMS_OVERUSED = 22,
  GLOBL__LOW_RESOURCES = 23,

  PILOT__ASTEROID_FELD = 24,
  PILOT__BLACK_HOLE = 25,
  PILOT__BONUS_MOVEMENT = 26,
  PILOT__FLIGHT_ROUTE_UPDATE = 27,
  PILOT__NAVIGATION_ERROR = 28,
  PILOT__SPACE_PIRATES = 29,

};

// PLEASE DON'T MOVE ANY ENUMS OUT OF THIS ORDER!
enum objective_cards
{
  OBJECTIVE_PLACEHOLDER = -1,
  BIG_ISSUE = 0,
  CLASS_ITEMS = 1,
  CLASS_SOLVER = 2,
  ISSUE_HELPER = 3,
  ISSUE_HELPER_15 = 4,
  ISSUE_SOLVER_10 = 5,
  ISSUE_SOLVER_15 = 6,
  ISSUE_SOLVER_5 = 7,
  MAJORITY_HELPER = 8,
  PERSONAL_ISSUE = 9,
  POINT_STASH = 10,
  UNHELPFUL = 11,
  UNHELPFUL_DICE = 12

};

// PLEASE DON'T MOVE ANY ENUMS OUT OF THIS ORDER!
enum item_cards
{
  ITEM_PLACEHOLDER = -1,
  COMMS__MICROPHONE = 0,
  COMMS__RADAR = 1,
  COMMS__RADIO = 2,
  COMMS__SCOUT_DRONE = 3,
  COMMS__UPGRADED_SPEAKERS = 4,

  ENGIN__SCREWDRIVER = 5,
  ENGIN__SCREWS = 6,
  ENGIN__TOOL_KIT = 7,
  ENGIN__WELDER = 8,
  ENGIN__WELDING_GOGGLES = 9,

  MEDIC__ANTIBIOTICS = 10,
  MEDIC__BANDAID = 11,
  MEDIC__FIRST_AID_KIT = 12,
  MEDIC__PAINKILLERS = 13,

  PILOT__MAP = 14,
  PILOT__NEW_CONTROLS = 15,
  PILOT__RADAR = 16,
  PILOT__THRUSTER_UPGRADE = 17,
  PILOT__WINDOW_WASH = 18,
};

#endif // PROJECT_CARDS_H
